---
title: "P8105_HW1_zc2555"
author: "Ziyu Chen"
date: "9/27/2021"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

First we need to create a data frame for question 1

```{r}
example_df = tibble(
   samp = rnorm(10),
   vector_logical = samp > 0,
   vector_char = c('a','a','a','b','b','b','c','c','c','c'),
   vector_factor = factor(x = vector_char,levels = c('a','b','c'))
)

mean(pull(example_df, samp))
mean(pull(example_df, vector_logical))
mean(pull(example_df, vector_char))
mean(pull(example_df, vector_factor))
```

The mean of samp is -0.4743189, the mean for vector_logical is 0.2. However, for vector_char and vector_factor, the pull function did not work.


Trying to convert variable to numeric type

```{r results='hide'}
as.numeric(pull(example_df, vector_logical))
as.numeric(pull(example_df, vector_char))
as.numeric(pull(example_df, vector_factor))
```

For variable vector_char, the conversion failed because vector_char are character variables

